### PR TITLE
Hopefully this fixed a ton of "float needs to be int" errors (feel free to revert if this doesn't work)

### PR DESCRIPTION
**Pull request by DeadSyntaxdev**
(also updates graphicsoptions.hx)

### CODE REVIEW

**Comment by DeadSyntaxdev** [comment]
I'm gonna try to fix this

**Comment by DeadSyntaxdev** [comment]
This seems to be a fatal error caused by LNK1120

**Comment by DeadSyntaxdev** [comment]
I somehow did get this to compile at first

**Comment by DeadSyntaxdev** [comment]
@SwickTheGreat any thoughts about what could be causing this error?

**Comment by EyeDaleHim** [comment]
These changes are intentional and are for HaxeFlixel 5.4.0.

**Comment by EyeDaleHim** [comment]
The reason these "Std.int" functions were removed was due to HaxeFlixel 5.4.0, it's always recommended to use the latest versions as Crow Engine is always prioritizing moving to the latest versions.

**Comment by DeadSyntaxdev** [comment]
> The reason these "Std.int" functions were removed was due to HaxeFlixel 5.4.0, it's always recommended to use the latest versions as Crow Engine is always prioritizing moving to the latest versions.

besides the point now, I updated my stuff and I can no longer compile. 
image

**Comment by DeadSyntaxdev** [comment]
While moving to the latest version is alright I do think it's a bit of a no-go at the moment unless it's just me having these problems. But it's unlikely as even github had problems compiling this on my fork with the same errors

**Comment by DeadSyntaxdev** [comment]
Also to for you to change the int to a float requires more than changing "int" to "float" I believe you have to write a variable for the float's number before you can pass it off as a float.

**Comment by EyeDaleHim** [comment]
I may consider overriding these classes entirely with new files until a fix is made for these libraries.

**Comment by DeadSyntaxdev** [comment]
That would probably be the best option at this moment "int"ime (yes I made a corny int joke get over it)

**Comment by DeadSyntaxdev** [comment]
Either that or revert to the last build that successfully compiled and redo functions that failed after that point.

**Comment by DeadSyntaxdev** [comment]
@EyeDaleHim Also I will say using floats where haxe expects an int is probably going to over complicate stuff.

**Comment by DeadSyntaxdev** [comment]
Alright I downgraded to a diff haxe version. all these errors are gone now, now I have to fix source code errors within the engine. If you want me to send you a fixed version my discord user is lexs_09

**Comment by DeadSyntaxdev** [comment]
it seems that haxe 4.3.2 just may not be good to use for now

**Pull request closed without merging**
